### ISSUE TITLE
Not able to add scroll bar

### ISSUE THREAD

**Issue by yunqu** [witchard/ipython-wavedrom#1]
When the waveform is too long, you end up with scaling down the entire graph to fit in the jupyter notebook. 

Is it possible to add scroll bar?

**Comment by witchard** [comment]
Hi yunqu - this is now fixed, please see https://github.com/witchard/ipython-wavedrom/commit/f8e1d4c5f98aa88e248093f8999fbebe2da1114f#diff-4baa9c9986b4d632442fe8ae9b4c59a8 for the code changes or take a look at the example notebook to see it in action.
