### ISSUE TITLE
Javascript error adding output

### ISSUE THREAD

**Issue by sshar14** [witchard/ipython-wavedrom#10]
![nbdraw](https://user-images.githubusercontent.com/49536908/55992316-1d059900-5c61-11e9-82ca-576e306a4e24.png)

Attached the image when running nbdraw in jupyter notebook. The image is correct but error is displayed.

**Comment by witchard** [comment]
I've removed the js version in favour of the newer wavedrom-cli so closing this issue. Please open a new issue if you have problems with the newer version.
