### ISSUE TITLE
Junk Error when drawing waveforms using the examples input 

### ISSUE THREAD

**Issue by Zwette** [witchard/ipython-wavedrom#11]
I ran the same code on jupyter notebook/lab, however I came across the problem as below.
![Screenshot from 2020-01-29 13-09-22](https://user-images.githubusercontent.com/41946061/73393291-a3df3d00-4298-11ea-9698-80a0a924842f.png)
![Screenshot from 2020-01-29 13-09-42](https://user-images.githubusercontent.com/41946061/73393298-a6da2d80-4298-11ea-9fae-9cff9ed828c8.png)

**Comment by ddompe** [comment]
I had the same error when using the Phantomjs from my distro. Just used latest from https://phantomjs.org/download.html and it worked

**Comment by witchard** [comment]
I've removed the js version in favour of the newer wavedrom-cli so closing this issue. Please open a new issue if you have problems with the newer version.
