### ISSUE TITLE
Save as SVG or PNG not working

### ISSUE THREAD

**Issue by tschinz** [witchard/ipython-wavedrom#3]
Hello,
I can create diagrams but rightclick on the image and save as png or svg doesn't seem to work.
1. is it possible to save the image file directly
2. is the rightclick freature working, is it a problem on my installation

I'm using jupyter python2
thanks

**Comment by witchard** [comment]
@tschinz, please could you confirm if this is working for you now? I have updated to the latest wavedrom which added the feature for saving svg/png.

**Comment by tschinz** [comment]
Hallo witchard,

I've just tested it and it is partially working. The right-click needs to be made at the lower edge to be able to click the `Save SVG` or `Save PNG` button.
![image](https://user-images.githubusercontent.com/1192968/28708127-59c834ea-737b-11e7-85ee-5248c1e42d17.png)
In the middle right-click not working

![image](https://user-images.githubusercontent.com/1192968/28708150-783e9d6a-737b-11e7-995a-70d09caed01e.png)
In the lower edge right-click working

**Comment by witchard** [comment]
Hmm, it was doing that for me - looks like it wasn't just for me! I think it might be to do with the way jupyter and wavedrom interact. I'll take a look when I get a chance.

**Comment by witchard** [comment]
I've removed the js version in favour of the newer wavedrom-cli so closing this issue.
