### ISSUE TITLE
Example notebook not rendering waveform on Github

### ISSUE THREAD

**Issue by yunqu** [witchard/ipython-wavedrom#4]
https://github.com/witchard/ipython-wavedrom/blob/master/example.ipynb

It seems that Github does not render the wavedrom properly. Is there a way to show wavedrom plots on Github?

**Comment by witchard** [comment]
@yunqu, I have updated the code to use the wavedrom-cli if the phantomjs tool is available. This does the rendering on the server side rather than in the browser and means that we end up storing an SVG file into the ipynb rather than javascript and html. It now renders correctly on github.
