### ISSUE TITLE
wavedrom cli runtime

### ISSUE THREAD

**Issue by drom** [witchard/ipython-wavedrom#8]
Hi @witchard 
Very nice tool! I am new to Jupiter, but I see that running Phantom + JS is pretty involved.
Does Jupiter has other popular JS engine? I am willing to make WaveDrom work with it better.

**Comment by witchard** [comment]
So, jupyter notebooks has the JS engine of the browser that the user is running it from - that is what  I use as the backup if phantomjs is not available, but doing that is a bit of a kludge as essentially I have to pass all the javascript to render the image directly back to the browser to do it's stuff.

A better way to integrate these two (in my opinion) would be if somehow the wavedrom javascript could be run in such a way that it generates an SVG image without the need for the a front-end based javascript engine like a browser or phaontomjs (i.e. without the need for the DOM). That way the rendering could take place using something like nodejs (or still even in the browser) and then the resultant SVG could just be returned to jupyter notebooks to draw.

Even better would be if it was written in python, but that may be a step to far 😈 .

**Comment by drom** [comment]
yes, 95% of wavedrom can be done outside of the DOM and browser. I use browser to measure text labels length and adjust labels column accordingly. Well I am thinking to rewrite wavedrom using React, then it will be much faster to render and will work outside of the DOM, in nodejs for example.
I have to learn more about Jupiter and Hydrogen. Have you tried Atom / Hydrogen?

**Comment by witchard** [comment]
I would have thought React would be quite nice as it has the server side rendering stuff, don't know much about it though. Not used hydrogen, my use case with jupyter notebook involves running it on a server and the browsing to it from my computer so I don't know if hydrogen supports that model.
