### ISSUE TITLE
Wavedrom not rendering correctly (displays a base64 encoded string of the js)

### ISSUE THREAD

**Issue by cfavi** [witchard/ipython-wavedrom#9]
Hello, 

I've been using this great nb extension successfully with an old version of jupyter. For some reasons I wanted to update to the latest Jupyter server and now all wavedrom examples are not rendering correctly anymore.

The output of the example usage: 
![image](https://user-images.githubusercontent.com/2091948/41531105-97a5380e-72f2-11e8-92c3-59adad52fa8d.png)

The output base64 decoded looks like js:
`'<script>var WaveSkin=WaveSkin||{};WaveSkin.default=["svg",{"id":"svg","xmlns":"http://www.w3.org/2000/svg","xmlns:xlink":"http://www.w3.org/1999/xlink","height":"0"},["style",{"type":"text/css"},"text{font-size:11pt;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;text-align:center;fill-opacity:1;font-family:Helvetica}.muted{fill:#aaa}. ...
`

The version of the notebook server is: 5.5.0
The server is running on this version of Python:
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 18:37:09) [MSC v.1500 64 bit (AMD64)]

**Comment by witchard** [comment]
I've removed the js version in favour of the newer wavedrom-cli so closing this issue. Please open a new issue if you have problems with the newer version.
